In [1]:
1+2

3

In [2]:
import numpy as np

# 1. Create a simple array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# 2. Basic math operations
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# 3. Reshape into a matrix
matrix = arr.reshape(5, 1)
print("Reshaped Matrix:\n", matrix)

# 4. Random numbers
rand_nums = np.random.randint(0, 10, size=(3, 3))
print("Random 3x3 Matrix:\n", rand_nums)

Array: [1 2 3 4 5]
Mean: 3.0
Standard Deviation: 1.4142135623730951
Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Random 3x3 Matrix:
 [[4 1 7]
 [1 6 7]
 [0 0 7]]


In [3]:
import pandas as pd

# 1. Create a DataFrame
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Score": [85, 90, 95, 88],
}
df = pd.DataFrame(data)
print("DataFrame:\n", df)

# 2. Basic statistics
print("Average Age:", df["Age"].mean())
print("Max Score:", df["Score"].max())

# 3. Filtering
print("People older than 30:\n", df[df["Age"] > 30])

# 4. Sorting
print("Sorted by Score:\n", df.sort_values(by="Score", ascending=False))

DataFrame:
       Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     88
Average Age: 32.5
Max Score: 95
People older than 30:
       Name  Age  Score
2  Charlie   35     95
3    David   40     88
Sorted by Score:
       Name  Age  Score
2  Charlie   35     95
1      Bob   30     90
3    David   40     88
0    Alice   25     85


In [1]:
import numpy as np
import pandas as pd

# Generate a 5x3 matrix of random values
values = np.random.rand(5, 3)

# Create DataFrame with custom row and column labels
df = pd.DataFrame(values, columns=["A", "B", "C"], index=["r1", "r2", "r3", "r4", "r5"])

print(df)

           A         B         C
r1  0.359818  0.873566  0.555976
r2  0.331371  0.113874  0.169983
r3  0.448356  0.534924  0.104993
r4  0.194665  0.045177  0.573460
r5  0.579713  0.549533  0.879442


In [2]:
students = [
    "Kwame",
    "Ama Serwaa",
    "Kojo_AI",
    "Akosua",
    f"Student_{101}",  # dynamic value
    "Yaw",
    "Efua Data",
    "Kofi",
    "Abena",
    "2026_batch",  # looks like a number but it's a string
]

# Length of array (same as total number of students)
length = len(students)
print("Length of array:", length)
print("Total number of students:", length)

# Access elements using negative indices
print("Index -4:", students[-4])  # 4th from the end
print("Index -6:", students[-6])  # 6th from the end
print("Index -8:", students[-8])  # 8th from the end

Length of array: 10
Total number of students: 10
Index -4: Efua Data
Index -6: Student_101
Index -8: Kojo_AI
